### ISSUE TITLE
Error while pairing Indoor hotspot:  "Characteristic 7731de63"

### ISSUE THREAD

**Issue by salmanfarisvp** [NebraLtd/hm-config#47] opened 2021-07-02 17:59 UTC
![image](https://user-images.githubusercontent.com/11945360/124312378-d4618f80-db8c-11eb-947e-51e2bd408ff2.png)

- [x] Done Factory Reset, But no change. 

Ref: 247747 
Related to: https://github.com/NebraLtd/maker-starter-app/issues/71

**Comment by shawaj** [comment] 2021-07-11 01:40
This one is the same as the emoji in the WiFi SSID one I think...

```
# WiFiSSID
WIFI_SSID_CHARACTERISTIC_UUID = "7731de63-bc6a-4100-8ab1-89b2356b038b"
WIFI_SSID_VALUE = "WiFi SSID"
```

#29

**Comment by shawaj** [comment] 2021-09-09 23:27
this relates to https://github.com/NebraLtd/hm-config/issues/92#issuecomment-916507140

It seems to be an issue as follows: 
- pair hotspot to diagnostics in app (or via add hotspot screen)
- come out of diagnostics
- try to run diagnostics again (or via add hotspot screen)
- this error is produced

if you wait 10 minutes, and then restart the bluetooth using the button, or you restart the hotspot or restart the gateway-config container then it will successfully pair again.

So it seems to be an issue with it still thinking it has a connection and not being able to kill the old one and restart or something like that...

**Comment by posterzh** [comment] 2021-11-16 12:56
This error was fixed after fixing `Incorrect password leads to characteristic error`(https://github.com/NebraLtd/hm-config/issues/105) by https://github.com/NebraLtd/hm-config/pull/129.

**Comment by posterzh** [comment] 2021-11-30 15:11
This is not fixed by https://github.com/NebraLtd/hm-config/issues/105. Opening again...

**Comment by posterzh** [comment] 2021-12-01 11:06
This issue is not reproducible in the outdoor and indoor hotspots with the current `hm-config` by @salmanfarisvp . The codebase related characteristics 7731de63 has been changed a lot since the reported date(Jul 02) to improve the quality and readability. 

What about closing this issue now and report a new issue if this characteristics error happens on the latest hotspot software?
https://nebraltd.slack.com/archives/C02JAACN6UX/p1638356081304800?thread_ts=1638210031.284900&cid=C02JAACN6UX

**Comment by KevinWassermann94** [comment] 2021-12-01 13:34
@salmanfarisvp Still has this exact error with the current version running on testnet?

**Comment by salmanfarisvp** [comment] 2021-12-02 11:27
@KevinWassermann94 Yes, it was the same. But after that, I was not able to reproduce it.

**Closed** 2022-04-28 21:06 UTC
Labels: bug, app
