### ISSUE TITLE
issue with hm-config container on RAK and OG (and possibly all other Pi 4 based) hotspots (gpio or libmraa issues - RuntimeError: Failed to add edge detection)

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-config#177] opened 2022-03-15 20:26 UTC
Seeing this on an original helium hotspot, and a couple of RAK units on the open fleet setup:
```
 gateway-config  upnpc : miniupnpc library test client, version 2.1.
 gateway-config   (c) 2005-2018 Thomas Bernard.
 gateway-config  Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
 gateway-config  for more information.
 gateway-config  List of UPNP devices found on the network :
 gateway-config   desc: http://192.168.1.149:38753/
 gateway-config   st: upnp:rootdevice
 gateway-config  
 gateway-config  No valid UPNP Internet Gateway Device found.
 gateway-config  Agent registered
[CHG] Controller E4:5F:01:3D:82:BF Pairable: yes
 gateway-config  [bluetooth]# pairable off
 gateway-config  [bluetooth]# quit
method return time=1647375130.488023 sender=org.freedesktop.DBus -> destination=:1.9398 serial=3 reply_serial=2
 gateway-config     array [
 gateway-config        string "org.freedesktop.DBus"
 gateway-config        string ":1.9398"
 gateway-config        string "com.helium.Miner"
 gateway-config        string ":1.8486"
 gateway-config     ]
 gateway-config  DBus is now accepting connections
 gateway-config  libmraa[12]: libmraa version v2.1.0-17-g10adedc initialised by user 'root' with EUID 0
 gateway-config  libmraa[12]: gpio: platform doesn't support chardev, falling back to sysfs
 gateway-config  libmraa[12]: libmraa initialised for platform 'Raspberry Pi Model B Rev 1' of type 5
 gateway-config  2022-03-15 20:12:11,662 - [DEBUG] - __main__ - (__main__.py).validate_env -- gatewayconfig/__main__.py:(52) - Starting with the following ENV:
 gateway-config          SENTRY_DSN=https://3234e2c67fe04c3e9f8b0c9b118c415a@o571444.ingest.sentry.io/5725518
 gateway-config          BALENA_APP_NAME=HELIUM-RAK
 gateway-config          BALENA_DEVICE_UUID=5c9c8b8b5b3631ee43adc923acfe6aa6
 gateway-config          VARIANT=COMP-RAKHM
 gateway-config          ETH0_MAC_ADDRESS_FILEPATH=/sys/class/net/eth0/address
 gateway-config          WLAN0_MAC_ADDRESS_FILEPATH=/sys/class/net/wlan0/address
 gateway-config          DIAGNOSTICS_JSON_URL=http://localhost/json
 gateway-config          ETHERNET_IS_ONLINE_FILEPATH=/sys/class/net/eth0/carrier
 gateway-config          FIRMWARE_VERSION=2022.03.07.0-2
 gateway-config  
 gateway-config  Traceback (most recent call last):
 gateway-config    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
 gateway-config      "__main__", mod_spec)
 gateway-config    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
 gateway-config      exec(code, run_globals)
 gateway-config    File "gatewayconfig/__main__.py", line 77, in <module>
 gateway-config      main()
 gateway-config    File "gatewayconfig/__main__.py", line 30, in main
 gateway-config      start()
 gateway-config    File "gatewayconfig/__main__.py", line 66, in start
 gateway-config      FIRMWARE_VERSION
 gateway-config    File "/opt/gatewayconfig/gatewayconfig_app.py", line 36, in __init__
 gateway-config      self.init_gpio(variant)
 gateway-config    File "/opt/gatewayconfig/gatewayconfig_app.py", line 99, in init_gpio
 gateway-config      self.user_button = Button(self.get_button_gpio(), hold_time=USER_BUTTON_HOLD_SECONDS)
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/devices.py", line 108, in __call__
 gateway-config      self = super(GPIOMeta, cls).__call__(*args, **kwargs)
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/input_devices.py", line 416, in __init__
 gateway-config      bounce_time=bounce_time, pin_factory=pin_factory)
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/mixins.py", line 433, in __init__
 gateway-config      super(HoldMixin, self).__init__(*args, **kwargs)
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/input_devices.py", line 171, in __init__
 gateway-config      self.pin.when_changed = self._pin_changed
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/pins/__init__.py", line 432, in <lambda>
 gateway-config      lambda self, value: self._set_when_changed(value),
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 319, in _set_when_changed
 gateway-config      self._enable_event_detect()
 gateway-config    File "/opt/venv/lib/python3.7/site-packages/gpiozero/pins/rpigpio.py", line 229, in _enable_event_detect
 gateway-config      bouncetime=self._bounce)
 gateway-config  RuntimeError: Failed to add edge detection
 gateway-config  Sentry is attempting to send 1 pending error messages
 gateway-config  Waiting up to 2 seconds
 gateway-config  Press Ctrl-C to quit
```

Some references:
Slack - https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1647375127495419
Balena device rak - https://dashboard.balena-cloud.com/devices/5c9c8b8b5b3631ee43adc923acfe6aa6/summary
Balena device rak 2 - https://dashboard.balena-cloud.com/devices/9c21f9001c11a9ffb42baf32e8615b00/summary
Balena device OG - https://dashboard.balena-cloud.com/devices/7597d8ef85262102132c96503c203910/summary

**Comment by shawaj** [comment] 2022-03-15 22:02
it definitely seems to be specific to rak and helium og units. I can’t seem to reproduce this on a sensecap (tried on 5). which implies an issue with gpio7 or one of the other gpios they use on rak / og

**Comment by shawaj** [comment] 2022-03-15 22:23
Apparently running with sudo can possibly fix this? https://forums.raspberrypi.com/viewtopic.php?f=32&t=125803

Seems to be a known issue with RPi.GPIO?

**Comment by vpetersson** [comment] 2022-03-16 08:35
>  Interesting that you've noticed the error doesn't occur when the program is run by the root user. Noted.

We're already [running as root](https://github.com/NebraLtd/hm-config/blob/master/Dockerfile), so `sudo` shouldn't be needed. 

Could potentially be something in Balena or Docker.

**Comment by shawaj** [comment] 2022-03-16 10:00
@vpetersson maybe. But also it seems to be mainly happening on rak and OG units. But not a huge sample size so not sure.

Would be interesting to try the retries thing mentioned

**Comment by MuratUrsavas** [comment] 2022-03-28 07:16
The problem is pretty obvious :) It was fixed for the testnet, but I don't have enough privileges to fix it in production fleet.

Could someone add `spi0-1cs` parameter into `dtoverlays` configuration of the fleet and remove all the device overrides? Then it will be fixed.

**Comment by vpetersson** [comment] 2022-03-28 08:19
I've added `"spi0-1cs,vc4-kms-v3d"` to the following fleets:

* HELIUM-RAK
* HELIUM-OG

**Comment by MuratUrsavas** [comment] 2022-03-28 08:30
@vpetersson They should be separate params. Could you fix it like `"spi0-1cs","vc4-kms-v3d"`?

**Comment by vpetersson** [comment] 2022-03-28 08:40
Fixed!

**Comment by MuratUrsavas** [comment] 2022-03-28 09:08
Everything has been defined for the production fleet.

**Closed by MuratUrsavas** 2022-03-28 09:08 UTC
Labels: bug

**Comment by shawaj** [comment] 2022-03-28 12:06
Ah strange. I thought those were already in there. But Balenacloud has been really buggy for me lately. I can't load that configuration page most of the time

Nice find anyway @MuratUrsavas

**Comment by shawaj** [comment] 2022-03-29 00:34
@MuratUrsavas why do we need "vc4-kms-v3d" ?

**Comment by shawaj** [comment] 2022-03-29 01:01
Weirdly, I deleted and re-added the fleet configuration for that DT param in the fleet that was in and it is now working. No idea why

**Comment by MuratUrsavas** [comment] 2022-03-29 06:36
That could be another Balena thing. It might not be actually applied on the device somehow.

**Comment by MuratUrsavas** [comment] 2022-03-29 06:38
> why do we need "vc4-kms-v3d" ?

For a possible future necessity. We might be using a remote display in one of our projects, and I don't want to debug many unrelated items just due to this. I know it is a veeery low probability. But who knows? :smile:
