### ISSUE TITLE
NMCLI No longer works

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/hm-config#36] opened 2021-06-26 15:17 UTC
The changes in PR #34 has broken NMCLI.

Error log:

```
 gateway-config  Exception in thread Thread-6:
 gateway-config  Traceback (most recent call last):
 gateway-config    File "/usr/local/lib/python3.7/dist-packages/nmcli/_system.py", line 38, in nmcli
 gateway-config      check=True, env={'LANG': 'C'})
 gateway-config    File "/usr/lib/python3.7/subprocess.py", line 487, in run
 gateway-config      output=stdout, stderr=stderr)
 gateway-config  subprocess.CalledProcessError: Command '['nmcli', '-t', '-f', 'IN-USE,SSID,MODE,CHAN,RATE,SIGNAL,SECURITY', 'device', 'wifi']' returned non-zero exit status 1.
 gateway-config  
 gateway-config  The above exception was the direct cause of the following exception:
 gateway-config  
 gateway-config  Traceback (most recent call last):
 gateway-config    File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
 gateway-config      self.run()
 gateway-config    File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/threading.py", line 69, in run
 gateway-config      reraise(*_capture_exception())
 gateway-config    File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/_compat.py", line 54, in reraise
 gateway-config      raise value
 gateway-config    File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/threading.py", line 67, in run
 gateway-config      return old_run_func(self, *a, **kw)
 gateway-config    File "/usr/lib/python3.7/threading.py", line 865, in run
 gateway-config      self._target(*self._args, **self._kwargs)
 gateway-config    File "config_program.py", line 1094, in wifiThreadCode
 gateway-config      wifiCache = nmcli.device.wifi()
 gateway-config    File "/usr/local/lib/python3.7/dist-packages/nmcli/_device.py", line 133, in wifi
 gateway-config      'device', 'wifi'])
 gateway-config    File "/usr/local/lib/python3.7/dist-packages/nmcli/_system.py", line 70, in nmcli
 gateway-config      'Unknown or unspecified error [code:%d, detail:%s]' % (rc, stderr)) from e
 gateway-config  nmcli._exception.UnspecifiedException: Unknown or unspecified error [code:1, detail:Error: Could not create NMClient object: Could not connect: No such file or directory.
 gateway-config  ]
 gateway-config  
 gateway-config  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): o571444.ingest.sentry.io:443
 gateway-config  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5725518/store/ HTTP/1.1" 200 41
```

**Comment by ryanteck** [comment] 2021-06-26 15:18
@robputt

**Comment by vpetersson** [comment] 2021-06-28 12:47
@robputt I know it's hard to debug this without physical hardware, but here are some leads:

If i pop a shell on the device within the container, the environment variable doesn't seem to be set properly:
```
root@204f46e:/opt/config-python# env | grep LANG
root@204f46e:/opt/config-python# 
```

This leads me to believe that the Dockerfile line `ENV LANG=C` is being suppressed by Balena for whatever reason. This hypothesis is easy to test using a simple container on Balena. If this is the case, we can always pass it on using the `docker-compose.yml` file instead.

**Comment by ryanteck** [comment] 2021-06-28 12:57
Or just revert the changes and it'll work again :)

And actually just running the docker container on a Pi would have flagged
this up. :)

**Comment by vpetersson** [comment] 2021-06-28 12:59
We definitely need a better test routine for this going forward. No doubt about this.

**Comment by vpetersson** [comment] 2021-06-28 16:37
@robputt, so looks like still isn't being passed on:

```
28.06.21 16:36:02 (+0000)  gateway-config  Agent registered
[CHG] Controller 00:1A:7D:DA:71:13 Pairable: yes
28.06.21 16:36:02 (+0000)  gateway-config  [bluetooth]# pairable off
28.06.21 16:36:02 (+0000)  gateway-config  [bluetooth]# quit
28.06.21 16:36:02 (+0000)  gateway-config  Agent registered
[CHG] Controller 00:1A:7D:DA:71:13 Pairable: yes
28.06.21 16:36:02 (+0000)  gateway-config  [bluetooth]# pairable off
28.06.21 16:36:02 (+0000)  gateway-config  [bluetooth]# quit
Starting 0
28.06.21 16:36:05 (+0000)  gateway-config  DEBUG:root:LED Thread Started
28.06.21 16:36:05 (+0000)  gateway-config  DEBUG:root:Diagnostics Thread Started
28.06.21 16:36:05 (+0000)  gateway-config  DEBUG:root:WiFi Thread Started
28.06.21 16:36:05 (+0000)  gateway-config  DEBUG:root:Advertising Thread Started
28.06.21 16:36:05 (+0000)  gateway-config  GATT application registered
28.06.21 16:36:05 (+0000)  gateway-config  GATT advertisement registered
28.06.21 16:36:10 (+0000)  gateway-config  DEBUG:root:Wi-Fi Scanning
28.06.21 16:36:11 (+0000)  gateway-config  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): o571444.ingest.sentry.io:443
28.06.21 16:36:11 (+0000)  gateway-config  Exception in thread Thread-6:
28.06.21 16:36:11 (+0000)  gateway-config  Traceback (most recent call last):
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/local/lib/python3.7/dist-packages/nmcli/_system.py", line 38, in nmcli
28.06.21 16:36:11 (+0000)  gateway-config      check=True, env={'LANG': 'C'})
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/lib/python3.7/subprocess.py", line 487, in run
28.06.21 16:36:11 (+0000)  gateway-config      output=stdout, stderr=stderr)
28.06.21 16:36:11 (+0000)  gateway-config  subprocess.CalledProcessError: Command '['nmcli', '-t', '-f', 'IN-USE,SSID,MODE,CHAN,RATE,SIGNAL,SECURITY', 'device', 'wifi']' returned non-zero exit status 1.
28.06.21 16:36:11 (+0000)  gateway-config  
28.06.21 16:36:11 (+0000)  gateway-config  The above exception was the direct cause of the following exception:
28.06.21 16:36:11 (+0000)  gateway-config  
28.06.21 16:36:11 (+0000)  gateway-config  Traceback (most recent call last):
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
28.06.21 16:36:11 (+0000)  gateway-config      self.run()
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/threading.py", line 69, in run
28.06.21 16:36:11 (+0000)  gateway-config      reraise(*_capture_exception())
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/_compat.py", line 54, in reraise
28.06.21 16:36:11 (+0000)  gateway-config      raise value
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/threading.py", line 67, in run
28.06.21 16:36:11 (+0000)  gateway-config      return old_run_func(self, *a, **kw)
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/lib/python3.7/threading.py", line 865, in run
28.06.21 16:36:11 (+0000)  gateway-config      self._target(*self._args, **self._kwargs)
28.06.21 16:36:11 (+0000)  gateway-config    File "config_program.py", line 1094, in wifiThreadCode
28.06.21 16:36:11 (+0000)  gateway-config      wifiCache = nmcli.device.wifi()
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/local/lib/python3.7/dist-packages/nmcli/_device.py", line 133, in wifi
28.06.21 16:36:11 (+0000)  gateway-config      'device', 'wifi'])
28.06.21 16:36:11 (+0000)  gateway-config    File "/usr/local/lib/python3.7/dist-packages/nmcli/_system.py", line 70, in nmcli
28.06.21 16:36:11 (+0000)  gateway-config      'Unknown or unspecified error [code:%d, detail:%s]' % (rc, stderr)) from e
28.06.21 16:36:11 (+0000)  gateway-config  nmcli._exception.UnspecifiedException: Unknown or unspecified error [code:1, detail:Error: Could not create NMClient object: Could not connect: No such file or directory.
28.06.21 16:36:11 (+0000)  gateway-config  ]
28.06.21 16:36:11 (+0000)  gateway-config  
28.06.21 16:36:12 (+0000)  gateway-config  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5725518/store/ HTTP/1.1" 200 41
```

I'm going to try reproducing this on a local Pi.

**Comment by shawaj** [comment] 2021-06-28 16:42
@ryanteck instead of wasting time putting smiley face emojis here and generally being difficult, perhaps you could actually help to document your code and handover in a constructive way? 

This has escalated to just needless troublemaking now.

**Comment by ryanteck** [comment] 2021-06-28 16:44
@shawaj The solution to the error I had fixed, it's been removed.

What exactly would you like me to do? Re-add in the work I've done that's been removed?

**Comment by shawaj** [comment] 2021-06-28 16:45
@ryanteck as I said above...

> perhaps you could actually help to document your code and handover in a constructive way?

**Comment by ryanteck** [comment] 2021-06-28 16:47
But this isn't something to do with documentation, this is that work is being deliberatley removed.

On the PR I explicitally said the reason why I done the solution the way I did, @vpetersson & @robputt ignored me and proceeded anyway.

The solution has been removed, it can be easily re-added. I can't see what else really is expected when my work is being ripped up.

**Comment by robputt** [comment] 2021-06-28 20:07
https://github.com/NebraLtd/hm-config/pull/39 < this PR implements the previous changes WITHOUT duplicating the entire nmcli code base. @vpetersson please can you pull it down to a test device and let me know how it works. I'll get a Pi configured tomorrow so I can poke around a bit more.

**Comment by shawaj** [comment] 2021-06-28 21:13
@robputt let us know if you need us to send you any hardware or anything

**Comment by robputt** [comment] 2021-06-29 06:30
Confirmed with @vpetersson the latest changes fix the nmcli issues and functionally tested on testnet device. Closing

**Closed by robputt** 2021-06-29 06:30 UTC
